export enum Category {
  Animal = 'Animal',
  Business = 'Business',
  Folks = 'Folks',
  Giving = 'Giving',
  Health = 'Health',
  Housing = 'Housing',
  Learn = 'Learn',
  Nature = 'Nature',
  Nutrition = 'Nutrition',
  Pray = 'Pray',
  Promise = 'Promise',
  Rest = 'Rest',
  Sport = 'Sport',
}
