export enum Category {
  Animal = 'Animal',
  Business = 'Business',
  Confession = 'Confession',
  Folks = 'Folks',
  Food = 'Food',
  Giving = 'Giving',
  Health = 'Health',
  Learn = 'Learn',
  Nature = 'Nature',
  Promise = 'Promise',
  Rest = 'Rest',
  Shelter = 'Shelter',
  Sport = 'Sport',
}
